# Generated by Django 3.1.3 on 2020-12-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='status',
            new_name='status_exact',
        ),
    ]
