# Generated by Django 3.1.3 on 2020-12-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201231_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='status_exact',
            new_name='status',
        ),
    ]
