# Generated by Django 3.1.3 on 2021-01-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210103_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_view_staff_member', 'Can view staff member'), ('can_renew', 'Can renew'))},
        ),
    ]
